/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe with per-dependency status.
         *
         *     The body inside ``data`` reports ``status="ok"`` when every probe
         *     reports ``ok``, otherwise ``status="degraded"``. The HTTP status is
         *     always 200 — callers inspect the envelope to make routing decisions.
         *
         *     Wrapped in the standard ``{ status, data, error }`` envelope (per
         *     Requirement 1.3) so the typed frontend client and every other route
         *     share one response shape.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Memories
         * @description Run the full upload pipeline for an uploaded WhatsApp ``.txt`` export.
         *
         *     The route enforces the demo-wide upload size cap before handing the file
         *     off to the parser; rejecting oversized payloads at the edge keeps the
         *     parser's input bounded and matches the documented ``FILE_TOO_LARGE``
         *     contract (Requirement 2.5).
         *
         *     Validates Requirements: 2.1, 2.5, 5.4.
         */
        post: operations["upload_memories_api_v1_memories_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Memories
         * @description Embed *body.query* and return the top-N matching chunks.
         *
         *     The vector store enforces session isolation structurally — every search
         *     pushes a ``session_id`` filter into Qdrant — so cross-session leakage is
         *     impossible regardless of what the LLM might suggest later.
         *
         *     Hits returned by the vector store carry a compact payload (text, source,
         *     timestamps, emotional metadata). To return the full :class:`MemoryChunk`
         *     shape the frontend renders, each hit is hydrated from the metadata store
         *     by ``chunk_id``. The envelope includes the similarity score alongside the
         *     chunk, which the frontend uses to render the relevance badge.
         *
         *     Results are returned in non-increasing similarity order (Property 8 /
         *     Requirement 6.4) — Qdrant's ``query_points`` already returns hits ranked
         *     by score descending, so we simply preserve that order.
         *
         *     Validates Requirements: 6.1, 6.2, 6.3, 6.4.
         */
        post: operations["search_memories_api_v1_memories_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/reflect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reflect
         * @description Generate a grounded :class:`ReflectionAnswer` for *body.message*.
         *
         *     Returns the standard envelope wrapping a :class:`ReflectionAnswer`.
         *     The reflector itself enforces the ethical preamble, retrieves the
         *     session-scoped context, and validates each sentence's grounding so
         *     only sub-threshold claims survive as ``[INFERENCE]`` markers.
         *
         *     Validates Requirements: 7.1, 7.5.
         */
        post: operations["reflect_api_v1_chat_reflect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialize Demo
         * @description Create a fresh demo session pre-loaded with the seed dataset.
         *
         *     Returns the standard envelope wrapping an :class:`InitializeDemoResponse`.
         *
         *     Raises
         *     ------
         *     ApiError(DEPENDENCY_DOWN)
         *         When the seed session has not been built yet (i.e., ``make seed``
         *         was never run in this deployment). The message includes the fix.
         */
        post: operations["initialize_demo_api_v1_demo_initialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_memories_api_v1_memories_upload_post */
        Body_upload_memories_api_v1_memories_upload_post: {
            /** File */
            file: string;
        };
        /**
         * EmotionalTone
         * @description The primary emotional tone assigned to a `MemoryChunk` by the enricher.
         *
         *     These values mirror the system prompt sent to Groq/LLaMA-3 in
         *     `app.services.enricher` — keep them in sync with that prompt and with the
         *     frontend's color/iconography mapping.
         * @enum {string}
         */
        EmotionalTone: "reflective" | "encouraging" | "anxious" | "grateful" | "uncertain" | "joyful" | "grieving" | "determined";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InitializeDemoRequest
         * @description `POST /api/v1/demo/initialize` request body (currently empty).
         */
        InitializeDemoRequest: Record<string, never>;
        /**
         * ReflectRequest
         * @description `POST /api/v1/chat/reflect` request body.
         */
        ReflectRequest: {
            /** Message */
            message: string;
            /** History */
            history?: components["schemas"]["ReflectionAnswerEntry"][] | null;
        };
        /**
         * ReflectionAnswerEntry
         * @description A single turn of prior chat history forwarded with a reflection request.
         */
        ReflectionAnswerEntry: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * SearchFilters
         * @description Optional metadata filters layered on top of vector similarity.
         */
        SearchFilters: {
            /** Tones */
            tones?: components["schemas"]["EmotionalTone"][] | null;
            /** Themes */
            themes?: components["schemas"]["ThematicTag"][] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
        };
        /**
         * SearchRequest
         * @description `POST /api/v1/memories/search` request body.
         */
        SearchRequest: {
            /**
             * Query
             * @description Natural-language search query.
             */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            filters?: components["schemas"]["SearchFilters"] | null;
        };
        /**
         * ThematicTag
         * @description High-level themes a `MemoryChunk` can be tagged with.
         *
         *     Per the design, the enricher returns 1–3 of these per chunk. The list-bound
         *     constraint is enforced at the model layer (`MemoryChunk.themes`).
         * @enum {string}
         */
        ThematicTag: "career" | "relationships" | "growth" | "loss" | "creativity" | "health" | "family" | "identity";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_memories_api_v1_memories_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_memories_api_v1_memories_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memories_api_v1_memories_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reflect_api_v1_chat_reflect_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    initialize_demo_api_v1_demo_initialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InitializeDemoRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
